import type {
  AutomationRule,
  Channel,
  Client,
  Meeting,
  Task,
} from "@/types/domain";

export const clients: Client[] = [
  {
    id: "c-001",
    full_name: "Daniel Cohen",
    phone: "+972-54-1122334",
    email: "daniel.cohen@mail.com",
    id_photo_url: "/mock/id-1.jpg",
    id_validated: true,
    poa_doc_url: "/mock/poa-1.pdf",
    inquiry_type: "life_insurance",
    status: "active",
    assigned_to: "Maya (Staff)",
    source_channel: "wa_office",
    last_service_date: "2024-02-10",
    created_at: "2026-03-28T09:15:00Z",
  },
  {
    id: "c-002",
    full_name: "Sarah Levi",
    phone: "+972-52-9988776",
    id_photo_url: "/mock/id-2.jpg",
    id_validated: false,
    inquiry_type: "health_insurance",
    status: "new",
    assigned_to: "Unassigned",
    source_channel: "wa_personal",
    created_at: "2026-04-12T14:02:00Z",
  },
  {
    id: "c-003",
    full_name: "Amir Dahan",
    phone: "+972-50-4433221",
    email: "amir.d@company.co.il",
    id_photo_url: "/mock/id-3.jpg",
    id_validated: true,
    poa_doc_url: "/mock/poa-3.pdf",
    inquiry_type: "pension",
    status: "completed",
    assigned_to: "Yossi (Owner)",
    source_channel: "email",
    last_service_date: "2025-11-04",
    created_at: "2025-10-20T11:30:00Z",
  },
  {
    id: "c-004",
    full_name: "Noa Friedman",
    phone: "+972-58-7766554",
    email: "noa.f@mail.com",
    id_photo_url: "/mock/id-4.jpg",
    id_validated: true,
    inquiry_type: "property",
    status: "active",
    assigned_to: "Maya (Staff)",
    source_channel: "wa_staff",
    created_at: "2026-04-08T08:45:00Z",
  },
  {
    id: "c-005",
    full_name: "Itai Shapira",
    phone: "+972-53-2211009",
    id_photo_url: "/mock/id-5.jpg",
    id_validated: false,
    inquiry_type: "vehicle",
    status: "new",
    assigned_to: "Unassigned",
    source_channel: "wa_office",
    created_at: "2026-04-13T16:20:00Z",
  },
];

export const meetings: Meeting[] = [
  {
    id: "m-001",
    client_id: "c-001",
    type: "zoom",
    scheduled_at: "2026-04-15T10:00:00Z",
    calendar_event_id: "gcal_abc123",
    recording_url: "/mock/recording-1.mp4",
    transcript:
      "Agent: Hi Daniel, thanks for joining. Let's go over your life insurance options...",
    summary_draft:
      "Client interested in 20-year term policy. Needs coverage of 1.5M NIS. Prefers monthly premium under 400 NIS.",
    summary_final:
      "Client interested in 20-year term policy. Coverage: 1.5M NIS. Monthly premium target: <400 NIS. Send 3 quotes from Harel, Migdal, Clal.",
    summary_status: "approved",
    client_confirmed: true,
    status: "done",
    reminder_24h_sent: true,
    reminder_1h_sent: true,
  },
  {
    id: "m-002",
    client_id: "c-004",
    type: "zoom",
    scheduled_at: "2026-04-16T13:30:00Z",
    calendar_event_id: "gcal_def456",
    summary_status: "draft",
    client_confirmed: false,
    status: "scheduled",
    reminder_24h_sent: true,
    reminder_1h_sent: false,
  },
  {
    id: "m-003",
    client_id: "c-003",
    type: "in_person",
    scheduled_at: "2025-11-02T09:00:00Z",
    calendar_event_id: "gcal_ghi789",
    summary_final: "Pension consolidation completed. All funds merged into Menorah.",
    summary_status: "sent",
    client_confirmed: true,
    status: "done",
    reminder_24h_sent: true,
    reminder_1h_sent: true,
  },
  {
    id: "m-004",
    client_id: "c-002",
    type: "phone",
    scheduled_at: "2026-04-17T11:00:00Z",
    calendar_event_id: "gcal_jkl012",
    summary_status: "draft",
    client_confirmed: false,
    status: "scheduled",
    reminder_24h_sent: false,
    reminder_1h_sent: false,
  },
];

export const tasks: Task[] = [
  {
    id: "t-001",
    client_id: "c-001",
    meeting_id: "m-001",
    type: "forms_check",
    description: "Verify forms sent to Harel, Migdal, Clal",
    assigned_to: "Maya (Staff)",
    due_at: "2026-04-22T09:00:00Z",
    status: "pending",
    reminder_sent: false,
    created_at: "2026-04-15T11:00:00Z",
  },
  {
    id: "t-002",
    client_id: "c-001",
    meeting_id: "m-001",
    type: "receipt_check",
    description: "Confirm insurance companies received documents",
    assigned_to: "Maya (Staff)",
    due_at: "2026-04-29T09:00:00Z",
    status: "pending",
    reminder_sent: false,
    parent_task_id: "t-001",
    created_at: "2026-04-15T11:00:00Z",
  },
  {
    id: "t-003",
    client_id: "c-003",
    meeting_id: "m-003",
    type: "policy_check",
    description: "Verify pension consolidation issued by Menorah",
    assigned_to: "Yossi (Owner)",
    due_at: "2025-12-02T09:00:00Z",
    status: "done",
    reminder_sent: true,
    created_at: "2025-11-04T10:00:00Z",
  },
  {
    id: "t-004",
    client_id: "c-003",
    meeting_id: "m-003",
    type: "deposit_check",
    description: "Confirm first deposit processed",
    assigned_to: "Yossi (Owner)",
    due_at: "2026-01-02T09:00:00Z",
    status: "done",
    reminder_sent: true,
    created_at: "2025-11-04T10:00:00Z",
  },
  {
    id: "t-005",
    client_id: "c-001",
    meeting_id: "m-001",
    type: "cross_check",
    description: "Cross-check all execution vs meeting summary",
    assigned_to: "Yossi (Owner)",
    due_at: "2026-06-15T09:00:00Z",
    status: "pending",
    reminder_sent: false,
    created_at: "2026-04-15T11:00:00Z",
  },
  {
    id: "t-006",
    client_id: "c-003",
    type: "service_meeting",
    description: "Biennial service meeting — schedule with client",
    assigned_to: "Yossi (Owner)",
    due_at: "2027-11-04T09:00:00Z",
    status: "pending",
    reminder_sent: false,
    created_at: "2026-04-01T08:00:00Z",
  },
  {
    id: "t-007",
    client_id: "c-002",
    type: "general",
    description: "Follow up — client has not re-uploaded valid ID",
    assigned_to: "Maya (Staff)",
    due_at: "2026-04-13T09:00:00Z",
    status: "overdue",
    reminder_sent: true,
    created_at: "2026-04-12T15:00:00Z",
  },
  {
    id: "t-008",
    client_id: "c-004",
    meeting_id: "m-002",
    type: "forms_check",
    description: "Prepare property insurance forms (post-meeting)",
    assigned_to: "Maya (Staff)",
    due_at: "2026-04-23T09:00:00Z",
    status: "pending",
    reminder_sent: false,
    created_at: "2026-04-16T14:00:00Z",
  },
];

export const automationRules: AutomationRule[] = [
  { id: 1, trigger: "new_lead_message", action: "Send initial response explaining intake process", timing: "Immediate", mode: "AUTO" },
  { id: 2, trigger: "document_uploaded", action: "Validate via OCR. If invalid: request re-upload", timing: "Immediate", mode: "AUTO" },
  { id: 3, trigger: "all_docs_valid", action: "Send Google Calendar meeting scheduling link", timing: "Immediate", mode: "AUTO" },
  { id: 4, trigger: "meeting_scheduled", action: "Send confirmation + pre-meeting reminders", timing: "-24h, -1h", mode: "AUTO" },
  { id: 5, trigger: "meeting_completed", action: "Generate transcription + summary draft", timing: "+30 min", mode: "AUTO" },
  { id: 6, trigger: "summary_generated", action: "Send to agent for human review and approval", timing: "Immediate", mode: "HYBRID" },
  { id: 7, trigger: "summary_approved", action: "Send to client for confirmation", timing: "Immediate", mode: "AUTO" },
  { id: 8, trigger: "client_confirms", action: "Forward summary + create task chain for staff", timing: "Immediate", mode: "AUTO" },
  { id: 9, trigger: "task_chain_created", action: "Check: forms sent to insurance company", timing: "+1 week", mode: "AUTO" },
  { id: 10, trigger: "forms_sent", action: "Check: received by insurance company", timing: "+2 weeks", mode: "AUTO" },
  { id: 11, trigger: "forms_received", action: "Check: policy/fund issued", timing: "+1 month", mode: "AUTO" },
  { id: 12, trigger: "policy_issued", action: "Check: first deposit completed", timing: "+2 months", mode: "AUTO" },
  { id: 13, trigger: "deposit_confirmed", action: "Cross-check execution vs. meeting summary", timing: "Immediate", mode: "HYBRID" },
  { id: 14, trigger: "last_service > 24mo", action: "Send proactive service meeting invitation", timing: "+24 months", mode: "AUTO" },
  { id: 15, trigger: "daily_cron_08:00", action: "Scan all channels, send missed inquiry digest", timing: "Daily 08:00", mode: "AUTO" },
];

export const channels: Channel[] = [
  { id: "ch-1", kind: "whatsapp", label: "WhatsApp Personal", identifier: "+972-54-9000001", unread_count: 3, last_scanned_at: "2026-04-14T08:00:00Z" },
  { id: "ch-2", kind: "whatsapp", label: "WhatsApp Office", identifier: "+972-3-6000000", unread_count: 12, last_scanned_at: "2026-04-14T08:00:00Z" },
  { id: "ch-3", kind: "whatsapp", label: "WhatsApp Staff (Maya)", identifier: "+972-54-9000002", unread_count: 5, last_scanned_at: "2026-04-14T08:00:00Z" },
  { id: "ch-4", kind: "email", label: "Office Email", identifier: "office@agency.co.il", unread_count: 8, last_scanned_at: "2026-04-14T08:00:00Z" },
  { id: "ch-5", kind: "email", label: "Owner Email", identifier: "yossi@agency.co.il", unread_count: 2, last_scanned_at: "2026-04-14T08:00:00Z" },
];

export const mockDataByKey = {
  clients,
  meetings,
  tasks,
} as const;
